#!/usr/bin/env bash
# docs-slice.sh — print only the part of a long docs file a cycle actually needs.
# Generated by `loopctl init`.
#
# WHY THIS EXISTS. On a real loop (shpce, 35 cycles, $204.35) a least-squares fit over the usage
# ledger put 78.4% of the bill on CACHE READ, not output: the cycle was paying to re-read a corpus
# that grows ~25 KB per ship. findings.md + handoff.md alone were 376,214 B of a 728 KB read.
# The lever is to narrow the READ, not to write less — see EFFICIENCY.md in the loopctl repo.
#
# WHAT IT DOES NOT DO, deliberately, because both were tried and are wrong:
#   * It does not SHARD the file. Citations of the form `findings.md:<line>` point into it from the
#     backlog and the review ledger (166 of them on shpce). Splitting invalidates every one of them
#     silently. The file stays whole and canonical; only the read is narrowed.
#   * It does not THIN built.md. The selector harvests every backticked token in that file, so prose
#     naming `res-03` is what marks that member built — thinning it re-dispatches finished work.
#
# READ-LESS AND WRITE-LESS ARE A PAIR. This tool narrows the READ; the pointer-map handoff block in
# builder.prompt.tmpl narrows the WRITE, so the corpus this slices over stops growing ~25 KB per ship
# in the first place. Slicing alone is bounded by how big the file got; together they bound both ends.
# Measured on the agent-parity loop's own 11 cycles (loopsim -context): file reads are 34% of the
# context bill at the median and 72% of them are docs, so slicing removes 17.7% of the whole bill.
#
# Output carries ORIGINAL line numbers (`223:<text>`, like grep -n), so a citation still resolves
# against a slice. That is the whole reason the numbers are printed rather than the lines re-flowed.
#
# Usage:
#   scripts/docs-slice.sh <findings|handoff|review|<file.md>> <id>...   sections for those ids
#   scripts/docs-slice.sh index <findings|handoff|review|<file.md>>     every heading, with its line
#
# A section runs from one `#`-heading to the next, and ownership is HIERARCHICAL: a heading with no id
# inherits its parent`s (a `### The numbers` under `## res-03 …` belongs to res-03). Only framing whose
# ancestors are also id-less — `# shpce findings`, `## APPARATUS` — is shared by every id, and it IS
# kept, because the per-ticket sections rest on it and dropping it would change conclusions.
# Getting that wrong is not a small miss: treating every id-less `###` as shared kept 185,924 B of
# findings.md instead of 24,397 B, because 67 of its 91 headings carry no id of their own.
# Everything before the first heading is always printed: that is the file`s own contract.
#
# Env: DOCS overrides the docs subdir (1brc), DOCS_ROOT overrides the repo root.
set -euo pipefail

DOCS="${DOCS:-1brc}"
ROOT="${DOCS_ROOT:-$(git rev-parse --show-toplevel)}"

resolve() { # <name> -> a readable path
  case "$1" in
    */*|*.md) printf '%s\n' "$1" ;;
    *) printf '%s\n' "$ROOT/docs/$DOCS/$1.md" ;;
  esac
}

usage() { echo "usage: docs-slice.sh <findings|handoff|review|file.md> <id>...   |   docs-slice.sh index <file>" >&2; exit 2; }

[ $# -ge 1 ] || usage

if [ "$1" = "index" ]; then
  [ $# -ge 2 ] || usage
  file="$(resolve "$2")"
  [ -r "$file" ] || { echo "docs-slice: cannot read $file" >&2; exit 1; }
  # Fence-aware, for the same reason the slice is: a `#` line inside a fenced block is not a heading, and
  # an index that lists a Python traceback as a section sends the next cycle to slice an id that does not exist.
  awk '/^[ \t]*(```|~~~)/ { fence = !fence; next } !fence && /^#+[ \t]/ { printf "%d:%s\n", NR, $0 }' "$file"
  exit 0
fi

file="$(resolve "$1")"
shift
[ $# -ge 1 ] || usage
[ -r "$file" ] || { echo "docs-slice: cannot read $file" >&2; exit 1; }

# Matching is by PREFIX IN EITHER DIRECTION, because headings abbreviate what the backlog spells out:
# a heading `### rev-46` must match the requested `rev-46-supersede-sweep-misses-and-miscounts`, and a
# heading `### res-12-riv-object-map` must match a requested `res-12`.
# The whole heading is scanned, not its first token: sections titled `### rev-46 + rev-47 + rev-48`
# were missed for every id but the first when only the first was read.
awk -v want="$*" '
function heading_ids(heading,   parts, np, i, j, tok, w, hasid) {
  hasid = 0
  np = split(tolower(heading), parts, /[^a-z0-9-]+/)
  for (i = 1; i <= np; i++) {
    tok = parts[i]
    # An id looks like <letters>-<digits>… (res-03, rev-46, grp-02, port-01, arch-01), plus final-dod.
    if (tok !~ /^[a-z]+-[0-9]+/ && tok != "final-dod") continue
    hasid = 1
    for (j = 1; j <= nw; j++) {
      w = ids[j]
      # PREFIX IN EITHER DIRECTION: headings abbreviate what the backlog spells out, so a heading
      # `### rev-46` must match a requested `rev-46-supersede-sweep-misses-and-miscounts`, and a
      # heading `### res-12-riv-object-map` must match a requested `res-12`.
      if (index(tok, w) == 1 || index(w, tok) == 1) return 1
    }
  }
  # 1 = mine, 0 = someone else`s, -1 = no id in this heading at all.
  return hasid ? 0 : -1
}
BEGIN { nw = split(tolower(want), ids, /[ \t]+/); keep = 1; keepAt[0] = 1 }
# A fenced block can contain lines starting with `#` that are NOT headings — findings.md carries a
# Python traceback whose `# AssertionError…` line would otherwise read as a level-1 heading and hand
# the whole rest of the file back to every id. Track fences first, and never parse inside one.
/^[ \t]*(```|~~~)/ { fence = !fence }
!fence && /^#+[ \t]/ {
  level = index($0 " ", " ") - 1        # count of leading #
  verdict = heading_ids($0)
  if (verdict == -1) {
    # No id in this heading: it INHERITS its parent section. A `### The numbers` under
    # `## res-03 …` belongs to res-03; only framing whose ancestors are also id-less
    # (`# shpce findings`, `## APPARATUS`) is shared by everyone, and that is what
    # keepAt[0] = 1 makes true.
    keep = keepAt[level - 1]
    for (l = level - 1; l >= 0 && keep == ""; l--) keep = keepAt[l]
  } else {
    keep = verdict
  }
  keepAt[level] = keep
  # Deeper levels must not inherit a stale sibling verdict.
  for (l = level + 1; l <= 6; l++) keepAt[l] = ""
}
keep { printf "%d:%s\n", NR, $0 }
' "$file"
